<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Import</title>
</head>
<body>
<form action="<?php echo $url->getUrl('upload','product'); ?>" method="post" enctype="multipart/form-data">
	<h3>Select File to Import:</h3>
	Select File to Upload :<input type="file" name="file" >
	<button type="submit">Uploads </button>
</form>
</body>
</html>