<form action="<?php echo $url->getUrl('save','shipping'); ?>" method="post">
	<table class="tc">
		<tr>
			<td><h3> SHIPPING METHOD</h3></td>
			<td>
				<a href="<?php echo $url->getUrl('grid','shipping'); ?>" class="btn btn-danger" >Cancel </a>
			</td>
			<td>
				<button type="submit" class="btn btn-success">SUBMIT</button>
			</td>
		</tr>
	</table>
	<br>
	<table border="1" cellspacing="0"  class="table table-striped table-bordered">
		
		<td class="tth"> Shipping method_id</td>
		<td>
			<input type="number" name="shipping[shipping_id]" placeholder="shipping_id">
		</td>
	</tr>
	<tr>
		<td class="tth"> Name</td>
		<td>
			<input type="text" name="shipping[name]" placeholder="name">
		</td>
	</tr>
	<tr>
		<td class="tth">Amount</td>
		<td>
			<input type="number" name="shipping[amount]" placeholder="amount">
		</td>
	</tr>
	<tr>
		<td class="tth">STATUS</td>
		<td>
			<select name="shipping[status]">
				<option value="active">Active</option>
				<option value="inactive">Inactive</option>
			</select>
		</td>
		
	</tr>
</table>
</form>
