<?php 
$row = $this->getData();
?>
      <form action="<?php echo $url->getUrl('save','shipping'); ?>" method="post">
         <table class="tc">
            <tr>
               <td class="heading">SAVE SHIPPING METHOD</td>
               <td>
                  <a href="<?php echo $url->getUrl('grid','shipping'); ?>" class="btn btn-danger">Cancel </a>
               </td>
               <td>
                  <button type="submit" class="btn btn-success">SAVE</button>
               </td>
            </tr>
         </table>
         <br>
         <table border="1" cellspacing="0"  class="table table-striped table-bordered ">
         <tr>
            <td class="tth"> Shipping method_id</td>
            <td>
               <input type="number" name="shipping[shipping_id]" placeholder="shipping_id" value="<?php echo $row->shipping_id; ?>">
            </td>
         </tr>
         <tr>
            <td class="tth"> Name</td>
            <td>
               <input type="text" name="shipping[name]" placeholder="name" value="<?php echo $row->name; ?>">
            </td>
         </tr>
         <tr>
            <td class="tth">Amount</td>
            <td>
               <input type="number" name="shipping[amount]" placeholder="amount" value="<?php echo $row->amount; ?>">
            </td>
         </tr>
         <tr>
            <td class="tth">STATUS</td>
            <td>
               <select name="shipping[status]">
                  <option value="active"<?php if($row->status =="active"){echo "selected";} ?>>Active</option>
                  <option value="inactive"<?php if($row->status =="inactive"){echo "selected";} ?>>Inactive</option>
               </select>
          </td>
       </tr>
    </table>
 </form>
