<?php 

$result = $this->medias->getData();
// echo "<pre>";
// print_r($this->getData());die;
?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>img view</title>
	<style type="text/css">
		
		.arrow{
			right: 200px;
		}
		.btn{
			float: right;
			margin-right: 100px;
			padding: 7px;
			margin-bottom: 10px;
		}
		.delete{
			float: right;
			margin-right: 150px;
			padding: 7px;
			margin-bottom: 10px;
		}
		.add{
			float: right;
			margin-right: 50px;
			padding: 7px;
			margin-bottom: 10px;
		}
		.view{
			margin-right: 50px;
			padding: 7px;
			margin-bottom: 10px;
		}
		.home{
			float: right;
			padding: 7px;
		}

	</style>
</head>
<body>
    <!-- <a href="Index.php?a=grid&c=Media" class="btn btn-primary" >Home</a>  -->
	<!-- <a href="Index.php?a=grid&c=Media" class="btn btn-primary p-2" >&larr;</a> -->
	<form action="Index.php?a=update&c=Media" method="POST" enctype="multipart/form-data">
	 <a href="Index.php?a=add&c=Media" class="btn btn-success">ADD IMAGES</a>
	<a href="Index.php?a=view&c=Media" class="btn btn-primary ">View Selection</a>
	<button type="submit" class="btn btn-success" >Submit </button>
	<table border="1" width="100%" cellpadding="10" align="center" class="table">
		<tr>
			<th>Image</th>
			<th>Media Id</th>
			<th>Base</th>
			<th>Thumb</th>
			<th>Small</th>
			<th>Gallery</th>
			<th>Created_at</th>
			<th>Delete</th>
		</tr>
			<?php foreach ($result as $rows): ?>
		<tr>
			<td> <img src="View/Media/img_list/<?php echo $rows->img_url; ?>" height="120" width="150" > </td>
			<td> <?php echo $rows->media_id; ?> </td>
			<td> <input type="radio" name="base" value="<?php echo $rows->media_id; ?>" > </td>
			<td> <input type="radio" name="thumb" value="<?php echo $rows->media_id; ?>" > </td>
			<td> <input type="radio" name="small" value="<?php echo $rows->media_id; ?>" > </td>
			<td>
				<input type="checkbox" name="gallery[]" value="<?php echo $rows->media_id; ?>" >
			</td>
			<td> <?php echo $rows->created_at; ?> </td> 
			<td>
				<a href="Index.php?a=delete&c=Media&id=<?php echo $rows->media_id; ?>">Delete</a>
			</td>
		</tr>
			<?php endforeach; ?>
		</table>
	</form>
</body>
</html>

