<?php 
$row = $this->getAdminData();
// echo "<Pre>";
// print_r($row);
?>
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>EDIT Admins</title>
   <style type="text/css">
      *{
         padding: 5px;
      }
      .content{
         border: 1px solid gray;
         height: 500px;
      }
      .tc{
         margin-left: auto;
         margin-right: auto;
      }
      .heading{
         font-size: 25px;
         font: bold;
      }
      .th{
         width: 14%;
      }
      .header{
         border: 1px solid gray;
         height: 55px;
      }
      .footer{
         border: 1px solid gray;
         height: 50px;
         text-align: center;
      }

   </style>
</head>
<body>
   <?php require_once 'C:\xampp\htdocs\NewProject\View\html\header.phtml'?>
   
   
   <div class="content">
      <br>
      <form action="<?php echo $url->getUrl('save','admin'); ?>" method="post">
         <table class="tc">
            <tr>
               <td class="heading">EDIT ADMINS</td>
               <td>
                  <a href="<?php echo $url->getUrl('grid','admin'); ?>">Cancel </a>
               </td>
               <td>
                  <button type="submit">SAVE</button>
               </td>
            </tr>
         </table>
         <br>
         <table border="1" cellspacing="0"  class="tc">
            
            <td class="tth"> Admin_Id</td>
            <td>
               <input type="number" name="admin[admin_id]" placeholder="admin_id" value="<?php echo $row->admin_id; ?>">
            </td>
         </tr>
         <tr>
            <td class="tth"> Name</td>
            <td>
               <input type="text" name="admin[name]" placeholder="name" value="<?php echo $row->name; ?>">
            </td>
         </tr>
         <tr>
            <td class="tth">Email</td>
            <td>
               <input type="email" name="admin[email]" placeholder="email" value="<?php echo $row->email; ?>">
            </td>
         </tr>
         <tr>
            <td class="tth">STATUS</td>
            <td>
               <select name="admin[status]">
                  <?php foreach($row->getTableClass()->getStatusOptions() as $key => $value): ?>
                  <?php $selected = ($key == $row->getStatus())? 'selected' : ''; ?>
                  <option value="<?php echo $key; ?>"<?php  echo $selected; ?>><?php echo $value; ?></option>
                  <?php endforeach; ?>
               </select>
          </td>
       </tr>
    </table>
 </form>
</div>

   <?php require_once 'C:\xampp\htdocs\NewProject\View\html\footer.phtml'?>
   


</body>
</html>