<?php 
$attribute = $this->attribute;
$options = $this->options;
?>

<form action="<?php echo $url->getUrl('save') ?>" method="post" class="p-3 border border-dark">
	<div class="row p-3">
	    <div class="col-4">
	        <h2>Save Attribute</h2>
	    </div>
	    <div class="col-2">
	        <button type="submit" class="btn btn-success">Save</button>
	    </div>
	</div>
  	<div class="form-group row mb-3 ms-3">
    	<label class="col-sm-2 col-form-label">Entity Type :</label>
    	<div class="col-sm-5">
	    	<select class="form-control" name="attribute[entity_type_id]">
	      		<?php foreach ($attribute->getEntityType() as $key => $value) :?>
                <option value="<?php echo $key ?>"><?php echo $value ?></option>
                <?php endforeach; ?>
	    	</select>
    	</div>
  	</div>
  	<div class="form-group row mb-3 ms-3">
    	<label class="col-sm-2 col-form-label">Code :</label>
    	<div class="col-sm-5">
      		<input type="text" class="form-control" name="attribute[code]" value="<?php echo $attribute->code; ?>">
    	</div>
  	</div>
  	<div class="form-group row mb-3 ms-3">
    	<label class="col-sm-2 col-form-label">Backend Type :</label>
    	<div class="col-sm-5">
      		<select class="form-control" name="attribute[backend_type]">
                <option value="int" <?php echo ($attribute->backend_type == 'int') ? 'selected':'' ?>>Integer</option>
                <option value="varchar" <?php echo ($attribute->backend_type == 'varchar') ? 'selected':'' ?>>Varchar</option>
                <option value="decimal" <?php echo ($attribute->backend_type == 'decimal') ? 'selected':'' ?>>Decimal</option>
                <option value="datetime" <?php echo ($attribute->backend_type == 'datetime') ? 'selected':'' ?>>Date and Type</option>
                <option value="text" <?php echo ($attribute->backend_type == 'text') ? 'selected':'' ?>>Text</option>
	    	</select>
    	</div>
  	</div>
	<div class="form-group row mb-3 ms-3">
    	<label class="col-sm-2 col-form-label">Name :</label>
    	<div class="col-sm-5">
      		<input type="text" class="form-control" name="attribute[name]" value="<?php echo $attribute->name; ?>">
    	</div>
  	</div>
  	<div class="form-group row mb-3 ms-3">
    	<label class="col-sm-2 col-form-label">Status :</label>
    	<div class="col-sm-5">
	    	<select class="form-control" name="attribute[status]">
	      		<?php foreach ($attribute->getResource()->getStatusOptions() as $key => $value) :?>
                <?php $selected = ($attribute->getStatus() == $key) ? 'selected':'' ?>
                <option value="<?php echo $key ?>" <?php echo $selected ?>><?php echo $value ?></option>
                <?php endforeach; ?>
	    	</select>
    	</div>
  	</div>
  	<div class="form-group row mb-3 ms-3">
    	<label class="col-sm-2 col-form-label">Backend Model :</label>
    	<div class="col-sm-5">
      		<input type="text" class="form-control" name="attribute[backend_model]" value="<?php echo $attribute->backend_model; ?>">
    	</div>
  	</div>
  	<div class="form-group row mb-3 ms-3">
    	<label class="col-sm-2 col-form-label">Input Type :</label>
    	<div class="col-sm-5">
      		<select class="form-control" name="attribute[input_type]" id="inputTypeSelect">
                <option value="textarea" <?php echo ($attribute->input_type == 'textarea') ? 'selected':'' ?>>Text Area</option>
                <option value="text" <?php echo ($attribute->input_type == 'text') ? 'selected':'' ?>>Text Box</option>
                <option value="select" <?php echo ($attribute->input_type == 'select') ? 'selected':'' ?>>Select</option>
                <option value="multiselect" <?php echo ($attribute->input_type == 'multiselect') ? 'selected':'' ?>>Multi-Select</option>
                <option value="radio" <?php echo ($attribute->input_type == 'radio') ? 'selected':'' ?>>Radio</option>
                <option value="checkbox" <?php echo ($attribute->input_type == 'checkbox') ? 'selected':'' ?>>Check-Box</option>
	    	</select>
    	</div>
  	</div>
	<div style="border: 1px solid red; display: none;margin: 10px 5px;" id="inputTypeOptionDiv">
		<table border="1">
			<thead>
			<tr>
				<th>&nbsp;</th>
				<th><input type="button" name="add" value="ADD" id="addOption"></th>
			</tr>
			<tr style="display: none;">
				<td><input type="text" name="option[exist][]"></td>
				<td><input type="button" name="remove" value="REMOVE" class="removeOption"></td>
			</tr>
			</thead>
			<tbody id="inputTypeOptionTable">
				<?php foreach ($options->getData() as $option) :?>
					<tr>
						<td><input type="text" name="option[exist][<?php echo $option->option_id ?>]" value="<?php echo $option->name ?>"></td>
						<td><input type="button" name="remove" value="REMOVE" class="removeOption"></td>
					</tr>
					<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</form>
<table style="display:none">
	<tbody id="inputTypeOptionDefault">
		<tr>
			<td><input type="text" name="option[new][]"></td>
			<td><input type="button" name="remove" value="REMOVE" class="removeOption"></td>
		</tr>
	</tbody>
</table>
<script type="text/javascript">
	$(".removeOption").click(function(){
		$(this).parent().parent().remove();
	});

	$("#addOption").click(function(){
		$('#inputTypeOptionTable').prepend($('#inputTypeOptionDefault').html());
	});

	$('#inputTypeSelect').change(function (){		
			var inputType = $(this);
			if(inputType.val() == 'select' || inputType.val() == 'multiselect' || inputType.val() == 'checkbox' || inputType.val() == 'radio'){
				$('#inputTypeOptionDiv').show();
			}
			else{
				$('#inputTypeOptionDiv').hide();
			}
	});

	$(document).ready(function (){	
		$('#inputTypeSelect').trigger('change');
	});
</script>