<?php 
$attributes = $this->getCollection()->getData();

?>
<div class="row p-3">
    <div class="col-10">
        <h2>Manage Attribute</h2>
    </div>
    <div class="col-2">
        <a class="btn btn-primary" href="<?php echo $url->getUrl('add') ?>">Add Attribute</a>
    </div>
</div>
<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>AttributeID</th>
			<th>Entity Type Id</th>
			<th>Code</th>
			<th>Backend Type</th>
			<th>Name</th>
			<th>Status</th>
			<th>backend Model</th>
			<th>Input Type</th>
			<th>Edit</th>
			<th>Delete</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($attributes as $attribute):?>
		<tr>
			<td><center><?php echo $attribute->attribute_id;?></center></td>
			<td><?php echo $attribute->entity_type_id; ?></td>
			<td><?php echo $attribute->code; ?></td>
			<td><?php echo $attribute->backend_type; ?></td>
			<td><?php echo $attribute->name; ?></td>
			<td><?php echo $attribute->status ?></td>
			<td><?php echo $attribute->backend_model; ?></td>
			<td><?php echo $attribute->input_type; ?></td>
			<td><a href="<?php echo $url->getUrl('edit',null,['id'=>$attribute->attribute_id]) ?>">Edit</td>
			<td><a href="<?php echo $url->getUrl('delete',null,['id'=>$attribute->attribute_id]) ?>">Delete</td>
		</tr>
		<?php endforeach; ?>
		
	</tbody>
</table>