<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Home Page</title>
	<script type="text/javascript" src="skin/jquery.min.js"></script>
	<script type="text/javascript" src="Skin/ajax.js"></script>

</head>

<body>
	<table border="1" width="100%" height="500px" cellpadding="4" class="table" cellspacing="0">
		<tr height="100px">
			<td colspan="3"><?php  $this->getChild('header')->render();?></td>
		</tr>
		<!-- <tr height="30px">
			 	<td colspan="3">Message</td>
		</tr> -->
		<tr>
			<!-- <td width="25%">Left</td> -->
			<td width="50%"><?php $this->getChild('content')->render(); ?></td>
			<!-- <td width="25%">Right</td> -->
		</tr>
		<tr height="50px">
			<td colspan="3"><?php $this->getChild('footer')->render(); ?></td>
		</tr>
	</table>
</body>
</html>