<form action="<?php echo $url->getUrl('insert','customer'); ?>" method="post">
	<table class="tc">
		<tr>
			<td class="heading"> <h3>ADD CUSTOMER</h3></td>
			<td>
				<a href="<?php echo $url->getUrl('grid','customer'); ?>">Cancel </a>
			</td>
			<td>
				<button type="submit">SUBMIT</button>
			</td>
		</tr>
	</table>
	<table border="1" cellspacing="0"  class="table table-striped table-bordered ">
		<tr>	
			<td class="tth"> Customer Id</td>
			<td>
				<input type="number" name="customer[customer_id]" placeholder="customer_id">
			</td>
		</tr>
		<tr>	
			<td class="tth"> first NAME</td>
			<td>
				<input type="text" name="customer[fname]" placeholder="first name">
			</td>
		</tr>
		<tr>
			<td class="tth"> last NAME</td>
			<td>
				<input type="text" name="customer[lname]" placeholder="lastname">
			</td>
		</tr>
		<tr>
			<td class="tth">EMAIL</td>
			<td>
				<input type="email" name="customer[email]" placeholder="email">
			</td>
		</tr>
		<tr>
			<td class="tth">GENDER</td>
			<td>
				<input type="radio" name="customer[gender]" value="male" checked>Male
				<input type="radio" name="customer[gender]" value="female">Female
				<input type="radio" name="customer[gender]" value="others">Others
			</td>
		</tr>
		<tr>
			<td class="tth">MOBILE</td>
			<td>
				<input type="number" name="customer[mobile]" placeholder="phone number">
			</td>
		</tr>
	</table>

		<table border="1" cellspacing="0" class="table table-striped table-bordered mt-5" >
		<tr>
			<th colspan="2">Customer Address</th>
		</tr>
		<tr>
			<td>Customer Id</td>
			<td><input type="text" name="customer[customer_id]" placeholder="customer_id"></td>
		</tr>
		<tr>
			<td>Address </td>
			<td><input type="text" name="address[address]" placeholder="Address" ></td>
		</tr>
		<tr>
			<td>country</td>
			<td><input type="text" name="address[country]" placeholder="country">  </td>
		</tr>
		<tr>
			<td>state</td>
			<td><input type="text" name="address[state]" placeholder="state">  </td>

		</tr>
		<tr>
			<td>city</td>
			<td><input type="text" name="address[city]" placeholder="city">  </td>

		</tr>
		<tr>
			<td>zipcode</td>
			<td><input type="number" name="address[zipcode]" placeholder="zipcode">  </td>

		</tr>

	</table>
</form>

