<?php 
$row = $this->getData();

?>
      <form action="" method="post" id="customer">
         <table class="tc">
            <tr>
               <td class="heading"> EDIT CUSTOMER</td>
              
               <td>
                  <button type="button" class="btn btn-success ms-5" onclick="ajax.setUrl('<?php echo $url->getUrl('update') ?>').setForm('customer').call()">SAVE</button>
               </td>
            </tr>
         </table>
         <br>
         <table border="1" cellspacing="0"  class="table table-striped table-bordered">
             
               <tr>  
                  <td class="tth"> Customer Id</td>
                  <td>
                     <input type="number" name="customer[customer_id]" placeholder="customer_id" value="<?php echo $row->customer_id; ?>">
                  </td>
               </tr>
               <td class="tth"> first NAME</td>
               <td>
                  <input type="text" name="customer[fname]" placeholder="first name" value="<?php echo $row->fname; ?>">
               </td>
            </tr>
            <tr>
               <td class="tth"> last NAME</td>
               <td>
                  <input type="text" name="customer[lname]" placeholder="lastname" value="<?php echo $row->lname; ?>">
               </td>
            </tr>
            <tr>
               <td class="tth">EMAIL</td>
               <td>
                  <input type="email" name="customer[email]" placeholder="email" value="<?php echo $row->email; ?>">
               </td>
            </tr>
            <tr>
               <td class="tth">GENDER</td>
               <td>
                  <input type="radio" name="customer[gender]"  value="male"<?php if($row->gender == "male"){ echo "checked";}   ; ?> >Male
                  <input type="radio" name="customer[gender]" value="female"<?php if($row->gender == "female"){ echo "checked";}   ; ?>> Female
                  <input type="radio" name="customer[gender]" value="others"<?php if($row->gender == "others"){ echo "checked";}   ; ?> >Others
               </td>
            </tr>
            <tr>
               <td class="tth">MOBILE</td>
               <td>
                  <input type="number" name="customer[mobile]" placeholder="phone number" value="<?php echo $row->mobile; ?>">
               </td>
            </tr>
      </table>

      <table border="1" cellspacing="0" class="table table-striped table-bordered mt-5" >
      <tr>
         <th colspan="2">Customer Address</th>
      </tr>
      <!-- <tr>
         <td>Customer Id</td>
         <td><input type="text" name="customer[customer_id]" placeholder="customer_id"></td>
      </tr> -->
      <tr>
         <td>Address </td>
         <td><input type="text" name="address[address]" placeholder="Address" value="<?php echo $row->address ;?>" ></td>
      </tr>
      <tr>
         <td>country</td>
         <td><input type="text" name="address[country]" placeholder="country" value="<?php echo $row->country; ?>">  </td>
      </tr>
      <tr>
         <td>state</td>
         <td><input type="text" name="address[state]" placeholder="state" value="<?php echo $row->state; ?>">  </td>

      </tr>
      <tr>
         <td>city</td>
         <td><input type="text" name="address[city]" placeholder="city" value="<?php echo $row->city; ?>">  </td>

      </tr>
      <tr>
         <td>zipcode</td>
         <td><input type="number" name="address[zipcode]" placeholder="zipcode" value="<?php echo $row->zipcode; ?>">  </td>

      </tr>
   </table>
   </form>

