<?php 

$row = $this->getCollection();
$customers = $this->getCustomers();

?>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Quote</title>
</head>
<body>
<h3>Order Table</h3>
<table>
	<tr>
		<td>Name : </td>
		<td>
			<select>
				<option><label>Select Customer </label></option>  
					<?php foreach($customers->getData() as $customer): ?>
				<option> <?php  echo $customer->fname ?> </option>
				<?php endforeach; ?>
			</select>
		</td>
	</tr>
</table>
</body>
</html>