<form action="<?php echo $url->getUrl('save','payment'); ?>" method="post">
	<table class="tc">
		<tr>
			<td><h3> PAYMENT METHOD</h3></td>
			<td>
				<a href="<?php echo $url->getUrl('grid','payment'); ?>" class="btn btn-danger ms-5">Cancel </a>
			</td>
			<td>
				<button type="submit" class="btn btn-success ms-2">SUBMIT</button>
			</td>
		</tr>
	</table>
	<br>
	<table border="1" cellspacing="0"  class="table table-striped table-bordered">
		<tr>
			<td class="tth"> payment method_id</td>
			<td>
				<input type="number" name="payment[payment_id]" placeholder="payment_id">
			</td>
		</tr>
		<tr>
			<td class="tth"> Name</td>
			<td>
				<input type="text" name="payment[name]" placeholder="name">
			</td>
		</tr>
		<tr>
			<td class="tth"> Amount</td>
			<td>
				<input type="number" name="payment[amount]" placeholder="amount">
			</td>
		</tr>
		<tr>
			<td class="tth">STATUS</td>
			<td>
				<select name="payment[status]">
					<option value="complete">Complete</option>
					<option value="pending">Pending</option>
				</select>
			</td>
		</tr>
	</table>
</form>
