<?php 
$payment = $this->getData();
?>
   <table class="tc">
      <tr>
         <td><h3>SAVE PAYMENT METHOD</h3></td>
         <td>
            <!-- <a href="<?php echo $url->getUrl('grid','payment'); ?>" class="btn btn-danger ms-5">Cancel </a> -->
         </td>
         <td>
            <button type="button" class="btn btn-success ms-2" onclick="ajax.setUrl('<?php echo $url->getUrl('save','payment') ?>').setForm('payment').call();">SAVE</button>
         </td>
      </tr>
   </table>
<form action="" method="post" id="payment">
   <table border="1" cellspacing="0"  class="table table-striped table-bordered">
      <tr>
         <td class="tth"> payment method_id</td>
         <td>
            <input type="number" name="payment[payment_id]" placeholder="payment_id" value="<?php echo $payment->payment_id; ?>">
         </td>
      </tr>
      <tr>
         <td class="tth"> Name</td>
         <td>
            <input type="text" name="payment[name]" placeholder="name" value="<?php echo $payment->name; ?>">
         </td>
      </tr>
      <tr>
         <td class="tth"> Amount</td>
         <td>
            <input type="text" name="payment[amount]" placeholder="amount" value="<?php echo $payment->amount; ?>">
         </td>
      </tr>
      <tr>
         <td class="tth">STATUS</td>
         <td>
            <select name="payment[status]">
               <option value="1" <?php if($payment->status=="1"){ echo "selected";} ?>>Active</option>
               <option value="2" <?php if($payment->status=="2"){ echo "selected";} ?>>Inactive</option>
            </select>
         </td>
      </tr>
   </table>
</form>
