<?php 
$row = $this->getData();
?>
<form action="" method="POST" id="category">
   <table class="tc">
      <tr>
         <td class="heading">SAVE CATEGORIES</td>
         <td>
            <!-- <a href="<?php echo $url->getUrl('grid','category'); ?>">Cancel </a> -->
         </td>
         <td>
            <button type="button" name="button" class="btn btn-success ms-5" onclick="ajax.setUrl('<?php 
            echo $url->getUrl('save')?>').setForm('category').call()">Save</button>
         </td>
      </tr>
   </table>
   <br>
   <table border="1" cellspacing="0"  class="table table-striped table-bordered">
     
         <td class="tth"> Category_id</td>
         <td>
            <input type="number" name="category[category_id]" placeholder="Category_id" value="<?php echo $row->category_id; ?>">
         </td>
      </tr>
      <tr>
         <td class="tth"> Name</td>
         <td>
            <input type="text" name="category[name]" placeholder="name" value="<?php echo $row->name; ?>" >
         </td>
      </tr>
      <tr>
         <td class="tth">Description</td>
         <td>
            <input type="text" name="category[description]" placeholder="Descritpion" value="<?php echo $row->description; ?>">
         </td>
      </tr>
      <tr>
         <td class="tth">STATUS</td>
         <td><select name="category[status]" >
            <option value="1" <?php if($row->status == "1"){echo "selected";} ?> >Active</option>
            <option value="2" <?php if($row->status == "2"){echo "selected";} ?> >InActive</option>
            </select>
         </td> 
      </tr>
   </table>
</form>

